# DDev Solr Cloud service file.
#
# To access Solr after it is installed:
# - The Solr admin interface will be accessible at:
#   http://<projectname>.ddev.site:8983
#   For example, if the project is named "myproject" the hostname will be:
#   http://myproject.ddev.site:8983
# - To access the Solr container from the web container use:
#   ddev-<project>-solr:8983
#
# To use this in your own project:
# 1. Copy this file and the solr (including security.json) directory to your project's ".ddev" directory.
# 2. For Drupal:
#      - enable the search_api_solr_admin (this sub-module included in Search API Solr >= 4.2.1)
#      - create a search server using the Solr Cloud Connector with Basic Auth using username "solr" and password
#        "SolrRocks".
#      - press the "Upload Configset" button.

version: '3.6'
services:
  solr1:
    image: solr:8
    container_name: ddev-${DDEV_SITENAME}-solr1
    expose:
      - 8983
    # These labels ensure this service is discoverable by ddev.
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    environment:
      SOLR_HOST: ddev-${DDEV_SITENAME}-solr1
      SOLR_PORT: 8983
      # The pre-trained OpenNLP models require a much bigger buffer.
      SOLR_OPTS: -Djute.maxbuffer=50000000
      #SOLR_HEAP: 1g
      ZK_HOST: ddev-${DDEV_SITENAME}-zoo:2181
      VIRTUAL_HOST: $DDEV_HOSTNAME
      HTTP_EXPOSE: 8983:8983
    depends_on:
      - zoo
    volumes:
      - .:/mnt/ddev_config
      - solr1:/var/solr
    command: bash -c "docker-entrypoint.sh solr zk cp file:/mnt/ddev_config/solr/security.json zk:/security.json && exec solr-foreground"

  solr2:
    image: solr:8
    container_name: ddev-${DDEV_SITENAME}-solr2
    expose:
      - 8984
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    environment:
      SOLR_HOST: ddev-${DDEV_SITENAME}-solr2
      SOLR_PORT: 8984
      # The pre-trained OpenNLP models require a much bigger buffer.
      SOLR_OPTS: -Djute.maxbuffer=50000000
      #SOLR_HEAP: 1g
      ZK_HOST: ddev-${DDEV_SITENAME}-zoo:2181
      VIRTUAL_HOST: $DDEV_HOSTNAME
      HTTP_EXPOSE: 8984:8984
    depends_on:
      - solr1
    volumes:
      - .:/mnt/ddev_config
      - solr2:/var/solr

  solr3:
    image: solr:8
    container_name: ddev-${DDEV_SITENAME}-solr3
    expose:
      - 8985
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    environment:
      SOLR_HOST: ddev-${DDEV_SITENAME}-solr3
      SOLR_PORT: 8985
      # The pre-trained OpenNLP models require a much bigger buffer.
      SOLR_OPTS: -Djute.maxbuffer=50000000
      #SOLR_HEAP: 1g
      ZK_HOST: ddev-${DDEV_SITENAME}-zoo:2181
      VIRTUAL_HOST: $DDEV_HOSTNAME
      HTTP_EXPOSE: 8985:8985
    depends_on:
      - solr1
    volumes:
      - .:/mnt/ddev_config
      - solr3:/var/solr

  zoo:
    image: bitnami/zookeeper:3.7
    container_name: ddev-${DDEV_SITENAME}-zoo
    hostname: ddev-${DDEV_SITENAME}-zoo
    expose:
      - 2181
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    environment:
      # The pre-trained OpenNLP models require a much bigger buffer.
      JVMFLAGS: -Djute.maxbuffer=50000000
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=ddev-${DDEV_SITENAME}-zoo:2888:3888
      ZOO_4LW_COMMANDS_WHITELIST: mntr, conf, ruok
      ALLOW_ANONYMOUS_LOGIN: "yes"
    volumes:
      - .:/mnt/ddev_config
      - zoo:/bitnami/zookeeper

  # This links the Solr service to the web service defined in the main
  # docker-compose.yml, allowing applications running inside the web container to
  # access the Solr service at http://solr:8983
  web:
    links:
      - solr1:solr

volumes:
  solr1:
  solr2:
  solr3:
  zoo:
